export type PuzzleType = 
  | '2x2' | '3x3' | '4x4' | '5x5' | '6x6' | '7x7'
  | 'mirror' | 'fisher' | 'axis' | 'windmill' | 'ghost' | 'morphix' | 'maple'
  | 'pyraminx' | 'master-pyraminx' | 'professor-pyraminx'
  | 'megaminx' | 'gigaminx' | 'kilominx'
  | 'skewb' | 'skewb-ultimate' | 'skewb-diamond'
  | 'curvy-copter' | 'helicopter' | 'dino'
  | 'square-1' | 'square-2' | 'ivy' | 'redi';

export interface PuzzleConfig {
  id: PuzzleType;
  name: string;
  category: 'Cubes' | 'Shape Mods' | 'Pyramids' | 'Dodeca' | 'Skew' | 'Curvy' | 'Other';
  faces: number;
  stickersPerFace: number;
  scannable: boolean;
  image: string;
  description: string;
}

export const PUZZLE_CONFIGS: Record<PuzzleType, PuzzleConfig> = {
  '2x2': {
    id: '2x2',
    name: '2×2 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 4,
    scannable: true,
    image: '/2x2-rubiks-cube-colorful-puzzle.jpg',
    description: 'Entry-level speedcube with 4 stickers per face',
  },
  '3x3': {
    id: '3x3',
    name: '3×3 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 9,
    scannable: true,
    image: '/3x3-classic-rubiks-cube-puzzle.jpg',
    description: 'Classic Rubik\'s cube with 9 stickers per face',
  },
  '4x4': {
    id: '4x4',
    name: '4×4 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 16,
    scannable: true,
    image: '/4x4-rubiks-cube-puzzle.jpg',
    description: 'Even-layered cube with 16 stickers per face',
  },
  '5x5': {
    id: '5x5',
    name: '5×5 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 25,
    scannable: true,
    image: '/5x5-rubiks-cube-puzzle.jpg',
    description: 'Odd-layered cube with 25 stickers per face',
  },
  '6x6': {
    id: '6x6',
    name: '6×6 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 36,
    scannable: true,
    image: '/6x6-rubiks-cube-puzzle.jpg',
    description: 'Even-layered cube with 36 stickers per face',
  },
  '7x7': {
    id: '7x7',
    name: '7×7 Cube',
    category: 'Cubes',
    faces: 6,
    stickersPerFace: 49,
    scannable: true,
    image: '/7x7-rubiks-cube-puzzle.jpg',
    description: 'Large odd-layered cube with 49 stickers per face',
  },
  'mirror': {
    id: 'mirror',
    name: 'Mirror Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/mirror-cube-puzzle-silver-metallic.jpg',
    description: 'Shape-mod with varying sizes instead of colors',
  },
  'fisher': {
    id: 'fisher',
    name: 'Fisher Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/fisher-cube-puzzle-diamond-shaped.jpg',
    description: 'Rotated 3×3 creating a diamond shape',
  },
  'axis': {
    id: 'axis',
    name: 'Axis Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/axis-cube-puzzle-diagonal-twisted.jpg',
    description: 'Diagonal axis rotation creating unique piece patterns',
  },
  'windmill': {
    id: 'windmill',
    name: 'Windmill Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/windmill-cube-puzzle-pinwheel.jpg',
    description: 'Twisted 3×3 with pinwheel-like appearance',
  },
  'ghost': {
    id: 'ghost',
    name: 'Ghost Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/ghost-cube-puzzle-stickerless.jpg',
    description: 'Stickerless shape-mod using only raised edges',
  },
  'morphix': {
    id: 'morphix',
    name: 'Master Morphix',
    category: 'Shape Mods',
    faces: 8,
    stickersPerFace: 6,
    scannable: false,
    image: '/master-morphix-puzzle-triangular.jpg',
    description: 'Pyraminx-like shape with 8 triangular faces',
  },
  'maple': {
    id: 'maple',
    name: 'Maple Leaf Cube',
    category: 'Shape Mods',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/maple-leaf-cube-puzzle-plus-pattern.jpg',
    description: 'Plus-sign shaped face pattern on each side',
  },
  'pyraminx': {
    id: 'pyraminx',
    name: 'Pyraminx',
    category: 'Pyramids',
    faces: 4,
    stickersPerFace: 9,
    scannable: false,
    image: '/pyraminx-puzzle-triangular-pyramid.jpg',
    description: 'Triangular pyramid with 4 faces',
  },
  'master-pyraminx': {
    id: 'master-pyraminx',
    name: 'Master Pyraminx',
    category: 'Pyramids',
    faces: 4,
    stickersPerFace: 16,
    scannable: false,
    image: '/master-pyraminx-puzzle-larger-pyramid.jpg',
    description: 'Larger pyramid variant',
  },
  'professor-pyraminx': {
    id: 'professor-pyraminx',
    name: 'Professor Pyraminx',
    category: 'Pyramids',
    faces: 4,
    stickersPerFace: 25,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Largest pyramid in the series',
  },
  'megaminx': {
    id: 'megaminx',
    name: 'Megaminx',
    category: 'Dodeca',
    faces: 12,
    stickersPerFace: 25,
    scannable: true,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Dodecahedron with 12 pentagonal faces',
  },
  'gigaminx': {
    id: 'gigaminx',
    name: 'Gigaminx',
    category: 'Dodeca',
    faces: 12,
    stickersPerFace: 36,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Larger dodecahedron puzzle',
  },
  'kilominx': {
    id: 'kilominx',
    name: 'Kilominx',
    category: 'Dodeca',
    faces: 12,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Smaller dodecahedron variant',
  },
  'skewb': {
    id: 'skewb',
    name: 'Skewb',
    category: 'Skew',
    faces: 6,
    stickersPerFace: 4,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Corner-rotating puzzle with 6 square faces',
  },
  'skewb-ultimate': {
    id: 'skewb-ultimate',
    name: 'Skewb Ultimate',
    category: 'Skew',
    faces: 6,
    stickersPerFace: 4,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Larger corner-rotating puzzle',
  },
  'skewb-diamond': {
    id: 'skewb-diamond',
    name: 'Skewb Diamond',
    category: 'Skew',
    faces: 8,
    stickersPerFace: 6,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Diamond-shaped corner-rotating puzzle',
  },
  'curvy-copter': {
    id: 'curvy-copter',
    name: 'Curvy Copter',
    category: 'Curvy',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Edge and corner-turning puzzle',
  },
  'helicopter': {
    id: 'helicopter',
    name: 'Helicopter Cube',
    category: 'Curvy',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Edge-turning puzzle creating unique rotations',
  },
  'dino': {
    id: 'dino',
    name: 'Dino Cube',
    category: 'Curvy',
    faces: 6,
    stickersPerFace: 6,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Corner-only turning puzzle',
  },
  'square-1': {
    id: 'square-1',
    name: 'Square-1',
    category: 'Other',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Shape-shifting puzzle with unique mechanics',
  },
  'square-2': {
    id: 'square-2',
    name: 'Square-2',
    category: 'Other',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Variant of Square-1',
  },
  'ivy': {
    id: 'ivy',
    name: 'Ivy Cube',
    category: 'Other',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Corner-edge turning puzzle',
  },
  'redi': {
    id: 'redi',
    name: 'Redi Cube',
    category: 'Other',
    faces: 6,
    stickersPerFace: 9,
    scannable: false,
    image: '/placeholder.svg?height=200&width=200',
    description: 'Corner and edge hybrid puzzle',
  },
};

export const CATEGORIES = ['Cubes', 'Shape Mods', 'Pyramids', 'Dodeca', 'Skew', 'Curvy', 'Other'] as const;
